### ISSUE TITLE
Remove test MetabolitesTests.tooManyInChIKeys

### ISSUE THREAD

**Issue by DeniseSl22** [BiGCAT-UM/imd-pathway-curation#2]
![image](https://user-images.githubusercontent.com/26277832/183893393-7470e462-f362-4b76-b988-4903c06bdf4d.png)

Upstream issue, not specific for IMD content

**Comment by egonw** [comment]
Done in https://github.com/BiGCAT-UM/imd-pathway-curation/commit/f194af838ef92700ecd6a3b6e805de7915915c9e
